spring:
  jpa:
    properties:
      hibernate:
        dialect: org.sqlite.hibernate.dialect.SQLiteDialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:sqlite:pgdb.db
    driver-class-name: org.sqlite.JDBC
    username:
    password:
